views/containers/__init__.py
from flask import Blueprint, render_template

from api import Client
from utils import admin_required

containers_page = Blueprint("containers", __name__, url_prefix="/containers")


@containers_page.route("/")
@admin_required
def index():
    c = Client()
    containers = c.portainer.containers()
    return render_template("containers/index.html", containers=containers)


@containers_page.route("/<container_id>")
@admin_required
def details(container_id):
    c = Client()
    container = c.portainer.containers(container_id)
    return render_template("containers/details.html", container=container)

templates/containers/details.html
{% extends "base.html" %}

{% block app_content %}
    <h1>
        <a href="{{config.APP_CONFIG.portainer_url}}#/containers/{{container.Id}}">
            {{container.Config.Labels["com.docker.compose.project"]}}/{{container.Config.Labels["com.docker.compose.service"]}}
        </a>
    </h1>
    
    <h4>Env</h4>
    <pre>{{container.Config.Env|join("\n")}}</pre>
    
    <pre>{{container|tojson(indent=4)}}</pre>
{% endblock %}

templates/containers/index.html
{% extends "base.html" %}
{% from "utils.html" import make_tabs %}

{% macro container_row(info) %}
    <div class="row">
        <div class="col">
            Image
        </div>
        <div class="col">
            <a href="{{urljoin('https://hub.docker.com/r/',info.Image)}}">{{info.Image}}</a>
        </div>
        <div class="col">
            Status
        </div>
        <div class="col">
            {{info.Status}}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Id: <a href="{{'{}#/containers/{}'.format(config.APP_CONFIG.portainer_url,info.Id)}}">{{info.Id}}</a>
        </div>
    </div>
    <div class="row">
        <pre>{{info|tojson(indent=4)}}</pre>
    </div>
{% endmacro %}

{% block app_content %}
    <h1>
        <a href="{{config.APP_CONFIG.portainer_url}}">Portainer</a>
    </h1>
    <table class="table table-sm table-bordered">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Image</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        {% for container in containers %}
            {% set label = container.Labels["com.docker.compose.service"] %}
                <tr>
                    <td>
                        <a href="{{url_for('containers.details',container_id=container.Id)}}">
                            {{container.Labels["com.docker.compose.project"]}}/{{container.Labels["com.docker.compose.service"]}}
                        </a>
                    </td>
                    <td>
                        <a href="{{urljoin('https://hub.docker.com/r/',container.Image)}}">{{container.Image}}</a>
                    </td>
                    <td>
                        {{container.Status}}
                    </td>
                </tr>
        {% endfor %}
    </table>
{% endblock %}