views/jellyfin/__init__.py
from flask import Blueprint, render_template
from flask_login import current_user

import stats_collect
from api import Client
from utils import login_required

jellyfin_page = Blueprint("jellyfin", __name__, url_prefix="/jellyfin")


@jellyfin_page.route("/")
@login_required
def index():
    c = Client()
    stats = stats_collect.Stats()
    jellyfin = {
        "info": c.jellyfin.system_info(),
        "status": c.jellyfin.status(),
        "counts": c.jellyfin.get_counts(),
        "library": stats["library"],
    }
    if not (current_user.is_authenticated and current_user.is_admin):
        jellyfin["library"] = {}
        jellyfin["status"]["HasUpdateAvailable"] = False
        jellyfin["status"]["HasPendingRestart"] = False

    return render_template("jellyfin/index.html", **jellyfin)


@jellyfin_page.route("/<item_id>")
@login_required
def details(item_id):
    c = Client()
    jellyfin = {
        "info": c.jellyfin.system_info(),
        "status": c.jellyfin.status(),
        "item": c.jellyfin.media_info(item_id),
    }
    if jellyfin["item"].get("Type") == "Movie":
        return render_template("jellyfin/movie.html", **jellyfin)
    if jellyfin["item"].get("Type") == "Series":
        return render_template("jellyfin/series.html", **jellyfin)
    return render_template("jellyfin/details.html", **jellyfin)

templates/jellyfin/details.html
{% extends "base.html" %}
{% from 'utils.html' import custom_render_form_row,make_tabs %}
{% from 'bootstrap/utils.html' import render_icon %}
{% from 'bootstrap/form.html' import render_form, render_field, render_form_row %}

{% block app_content %}

<h2><a href={{info.LocalAddress}}>Jellyfin</a> v{{info.Version}}</h2>
{% if status.HasUpdateAvailable %}
    <h3>Update available</h3>
{% endif %}
{% if status.HasPendingRestart %}
    <h3>Restart pending</h3>
{% endif %}

<img src={{cfg.jellyfin_url}}/Items/{{item.Id}}/Images/Art>

<pre>{{item|pformat}}</pre>

{% endblock %}

templates/jellyfin/index.html
{% extends "base.html" %}
{% from 'utils.html' import custom_render_form_row,make_tabs %}
{% from 'bootstrap/utils.html' import render_icon %}
{% from 'bootstrap/form.html' import render_form, render_field, render_form_row %}

{% macro make_row(title,items) %}
    <div class="d-flex flex-wrap">
    {% for item in items %}
        {{item|safe}}
    {% endfor %}
    </div>
{% endmacro %}

{% macro make_tabs(tabs) %}
    <div class="row">
        <div class="col">
            <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                {% for (label,_) in tabs %}
                    {% set slug = (label|slugify) %}
                    {% if not (loop.first and loop.last) %}
                    <li class="nav-item">
                        <a class="nav-link {{'active' if loop.first}}" id="nav-{{slug}}-tab" data-toggle="pill" href="#pills-{{slug}}" role="tab" aria-controls="pills-{{slug}}" aria-selected="{{loop.first}}">
                            {{label}}
                        </a>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
    
    <div class="tab-content" id="searchResults">
        {% for (label,items) in tabs %}
            {% set slug = (label|slugify) %}
            <div class="tab-pane fade {{'show active' if loop.first}}" id="pills-{{slug}}" role="tabpanel" aria-labelledby="nav-{{slug}}-tab">
                {{make_row(label,items)}}
            </div>
        {% endfor %}
    </div>
{% endmacro %}

{% macro make_table(items) %}
    <table class="table table-sm table-bordered">
        {% for item in items|sort(attribute="Name")%}
            <tr>
                <td><a href="{{url_for('jellyfin.details',item_id=item.Id)}}">{{item.Name}}</a> ({{item.ProductionYear}})</td>
            </tr>
        {% endfor %}
    </table>
{% endmacro %}

{% block app_content %}
    <h1><a href={{info.LocalAddress}}>Jellyfin</a> v{{info.Version}}</h1>
    {% if status.HasUpdateAvailable %}
        <h3>Update available</h3>
    {% endif %}
    {% if status.HasPendingRestart %}
        <h3>Restart pending</h3>
    {% endif %}

    <h3>Library statistics</h3>

    <table class="table table-sm table-bordered">
            {% for name, value in counts.items() %}
                {% if value != 0 %}
                    <tr>
                        <td>{{name}}</td>
                        <td>{{value}}</td>
                    </tr>
                {% endif %}
            {% endfor %}
    </table>
    {% if library %}
        <h3>{{library|count}} Items</h3>
    {% endif %}

    {% set tabs = [] %}
    {% for title,group in library.values()|groupby("Type") %}
        {% do tabs.append((title,[make_table(group)])) %}
    {% endfor %}
    {{make_tabs(tabs)}}
{% endblock %}

templates/jellyfin/movie.html
{% extends "base.html" %}
{% from 'utils.html' import custom_render_form_row,make_tabs %}
{% from 'bootstrap/utils.html' import render_icon %}
{% from 'bootstrap/form.html' import render_form, render_field, render_form_row %}

{% block app_content %}

<h1><a href={{info.LocalAddress}}>Jellyfin</a> v{{info.Version}}</h1>
{% if status.HasUpdateAvailable %}
    <h3>Update available</h3>
{% endif %}
{% if status.HasPendingRestart %}
    <h3>Restart pending</h3>
{% endif %}

<div class="row">
    <div class="col">
        {% for ext in item.ExternalUrls %}
            <a href={{ext.Url}}><span class="badge badge-secondary">{{ext.Name}}</span></a>
        {% endfor %}
    </div>
</div>

<h2 title="{{item.Id}}">
{{item.Name}}
{% if item.IsHD %}
<span class="badge badge-primary">HD</span>
{% endif %}
</h2>
<p>{{item.Overview}}</p>

<hr>

{#  <img src={{info.LocalAddress}}/Items/{{item.Id}}/Images/Primary>  #}

{% set data = [
    ("Path", item.Path),
    ("Genres", item.Genres|join(", ")),
] %}

<div class="row">
    <div class="col">
        <table class="table table-sm table-bordered">
        {% for k,v in data %}
            <tr>
                <td>{{k}}</td>
                <td>{{v}}</td>
            </tr>
        {% endfor %}
        </table>
    </div>
</div>

<pre>{{item|pformat}}</pre>

{% endblock %}

templates/jellyfin/series.html
{% extends "base.html" %}
{% from 'utils.html' import custom_render_form_row,make_tabs %}
{% from 'bootstrap/utils.html' import render_icon %}
{% from 'bootstrap/form.html' import render_form, render_field, render_form_row %}

{% block app_content %}

<h1><a href={{info.LocalAddress}}>Jellyfin</a> v{{info.Version}}</h1>
{% if status.HasUpdateAvailable %}
    <h3>Update available</h3>
{% endif %}
{% if status.HasPendingRestart %}
    <h3>Restart pending</h3>
{% endif %}

<h2 title="{{item.Id}}"><a href="{{info.LocalAddress}}/web/index.html#!/details?id={{item.Id}}">{{item.Name}}</a></h2>

<div class="row">
    <div class="col">
        {% for ext in item.ExternalUrls %}
            <a href={{ext.Url}}><span class="badge badge-secondary">{{ext.Name}}</span></a>
        {% endfor %}
    </div>
</div>

<div class="text-center">
    <img class="rounded" src={{info.LocalAddress}}/Items/{{item.Id}}/Images/Primary>
</div>

<p>{{item.Overview}}</p>


<div class="row">
    <div class="col">
        <table class="table table-sm table-bordered">
            <tr>
                <td>Path</td>
                <td>{{item.Path}}</td>
            </tr>
        </table>
    </div>
</div>

<div>
    {% for season in item.Seasons %}
    <div class="row">
        <div class="col">
            <h3>{{season.Name}}</h3>
            <table class="table table-sm table-bordered">
            {% for episode in season.Episodes %}
                <tr>
                    <td>{{episode.Name}}</td>
                </tr>
            {% endfor %}
            </table>
        </div>
    </div>
    {% endfor %}
</div>

<table class="table table-sm table-bordered">
{% for k,v in item|flatten %}
    <tr>
        <td>{{k}}</td>
        <td>{{v}}</td>
    </tr>
{% endfor %}
</table>

{% endblock %}