views/remote/__init__.py
import base64
import hashlib
import io

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.serialization import load_ssh_public_key
from flask import Blueprint, redirect, render_template, request, url_for, Markup, flash

from forms import AddSSHUser
from api import Client
from utils import admin_required

remote_page = Blueprint("remote", __name__, url_prefix="/remote")


def ssh_fingerprint(key):
    fp = hashlib.md5(base64.b64decode(key)).hexdigest()
    return ":".join(a + b for a, b in zip(fp[::2], fp[1::2]))


@remote_page.route("/stop")
@admin_required
def stop():
    c = Client()
    session_id = request.args.get("session")
    c.jellyfin.stop_session(session_id)
    return redirect(url_for("remote.index"))


@remote_page.route("/")
@admin_required
def index():
    c = Client()
    res = c.ssh.get("/data/.ssh/authorized_keys", io.BytesIO())
    res.local.seek(0)
    ssh_keys = []
    for key in str(res.local.read(), "utf8").splitlines():
        disabled = False
        if key.startswith("#"):
            key = key.lstrip("#").lstrip()
            disabled = True
        load_ssh_public_key(bytes(key, "utf8"))
        key_type, key, name = key.split(None, 2)
        ssh_keys.append(
            {
                "disabled": disabled,
                "type": key_type,
                "key": key,
                "fingerprint": ssh_fingerprint(key),
                "name": name,
            }
        )
    key = request.args.get("key")
    enabled = request.args.get("enabled")
    if not (key is None or enabled is None):
        key_file = []
        for ssh_key in ssh_keys:
            if ssh_key["key"] == key:
                ssh_key["disabled"] = enabled == "False"
            if ssh_key["disabled"]:
                key_file.append("#{type} {key} {name}".format(**ssh_key))
            else:
                key_file.append("{type} {key} {name}".format(**ssh_key))
        buf = io.BytesIO(bytes("\n".join(key_file), "utf8"))
        c.ssh.put(buf, "/data/.ssh/authorized_keys", preserve_mode=False)
        return redirect(url_for("remote"))
    jellyfin = {
        "users": c.jellyfin.get_users(),
        "sessions": c.jellyfin.sessions(),
        "info": c.jellyfin.system_info(),
    }
    return render_template(
        "remote/index.html",
        ssh=ssh_keys,
        jellyfin=jellyfin)


@remote_page.route("/add", methods=["GET", "POST"])
@admin_required
def add():
    form = AddSSHUser()
    c = Client()
    if form.validate_on_submit():
        key = load_ssh_public_key(bytes(form.data["ssh_key"], "utf8"))
        rawKeyData = key.public_bytes(
            encoding=serialization.Encoding.OpenSSH,
            format=serialization.PublicFormat.OpenSSH,
        )
        passwd = c.add_user(form.data["name"], str(rawKeyData, "utf8"))
        flash(
            Markup(
                "".join(
                    [
                        f"<p>Name: <b>{form.data['name']}</b></p>",
                        f"<p>PW: <b>{passwd}</b></p>",
                        f"<p>FP: <b>{ssh_fingerprint(rawKeyData.split()[1])}</b></p>",
                    ])))
    return render_template("remote/add.html", form=form)

templates/remote/add.html
{% extends "base.html" %}
{% from 'utils.html' import custom_render_form_row,make_tabs %}
{% from 'bootstrap/form.html' import render_form, render_field, render_form_row %}

{% block app_content %}

{% if form %}
<h1>Grant remote access</h1>
{% endif %}

<div class="row">
    <div class="col-lg">
        <form method="post" class="form">
            {{form.csrf_token()}}
            {{custom_render_form_row([form.name])}}
            {{custom_render_form_row([form.ssh_key])}}
            {{custom_render_form_row([form.add])}}
        </form>
    </div>
</div>


{% endblock %}

templates/remote/index.html
{% extends "base.html" %}
{% from 'utils.html' import custom_render_form_row,make_tabs %}
{% from 'bootstrap/utils.html' import render_icon %}
{% from 'bootstrap/form.html' import render_form, render_field, render_form_row %}

{% block app_content %}

<h1>
Remote access <a href={{url_for("remote.add")}}>{{render_icon("person-plus-fill")}}</a>
</h1>

<div class="row">
    <div class="col-lg">
        <h4>SSH</h4>
        <table class="table table-sm table-bordered">
            <tr>
                <th></th>
                <th>Type</th>
                <th>Key fingerprint</th>
                <th>Name</th>
            </tr>
            {% for key in ssh %}
                <tr {{ {"class":"text-muted" if key.disabled else none}|xmlattr }}>
                    <td>
                        {% if key.disabled %}
                            <a href="{{url_for("remote.index",enabled=True,key=key.key)}}">{{render_icon("person-x-fill",color='danger')}}</a>
                        {% else %}
                            <a href="{{url_for("remote.index",enabled=False,key=key.key)}}">{{render_icon("person-check-fill",color='success')}}</a>
                        {% endif %}
                    </td>
                    <td>{{key.type}}</td>
                    <td title="{{key.key}}">{{key.fingerprint}}</td>
                    <td>{{key.name}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

<div class="row">
    <div class="col-lg">
        <h4>Active Streams</h4>
        <table class="table table-sm table-bordered">
            <tr>
                <th>Episode</th>
                <th>Show</th>
                <th>Language</th>
                <th>User</th>
                <th>Device</th>
                <th>Mode</th>
            </tr>
            {% for session in jellyfin.sessions %}
                {% if "NowPlayingItem" in session %}
                    {% with np=session.NowPlayingItem, ps=session.PlayState%}
                    <tr>
                        <td>
                            {% if session.SupportsMediaControl %}
                            <a href="{{url_for('remote.stop',session=session.Id)}}">
                                {{render_icon("stop-circle")}}
                            </a>
                            {% endif %}
                            <a title="{{ps.MediaSourceId}}" href="{{cfg().jellyfin_url}}web/index.html#!/details?id={{np.Id}}">
                                {{np.Name}}
                            </a>
                            ({{(ps.PositionTicks/10_000_000)|timedelta(digits=0)}}/{{(np.RunTimeTicks/10_000_000)|timedelta(digits=0)}})
                            {% if ps.IsPaused %}
                                (Paused)
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{cfg().jellyfin_url}}web/index.html#!/details?id={{np.SeriesId}}">
                                {{np.SeriesName}}
                            </a>
                            <a href="{{cfg().jellyfin_url}}web/index.html#!/details?id={{np.SeasonId}}">
                                ({{np.SeasonName}})
                            </a>
                        </td>
                        <td>
                            {% if ("AudioStreamIndex" in ps) and ("SubtitleStreamIndex" in ps) %}
                                {% if ps.AudioStreamIndex == -1 %}
                                    {% set audio_lang = "-" %}
                                {% else %}
                                    {% set audio_lang = np.MediaStreams[ps.AudioStreamIndex].Language or "?" %}
                                {% endif %}
                                {% if ps.SubtitleStreamIndex == -1 %}
                                    {% set subtitle_lang = "-" %}
                                {% else %}
                                    {% set subtitle_lang = np.MediaStreams[ps.AudioStreamIndex].Language or "?" %}
                                {% endif %}
                                {{audio_lang}}/{{subtitle_lang}}
                            {% else %}
                                ?/?
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{cfg().jellyfin_url}}web/index.html#!/useredit.html?userId={{session.UserId}}">
                                {{session.UserName}}
                            </a>
                        </td>
                        <td>
                            {{session.DeviceName}}
                        </td>
                        <td>
                            {% if ps.PlayMethod =="Transcode" %}
                                <p title="{{session.TranscodingInfo.Bitrate|filesizeformat(binary=False)}}/s | {{session.TranscodingInfo.CompletionPercentage|round(2)}}%">
                                    {{ps.PlayMethod}}
                                </p>
                            {% else %}
                            <p>
                                {{ps.PlayMethod}}
                            </p>
                            {% endif %}
                        </td>
                    </tr>
                    {% endwith %}
                {% endif %}
            {% endfor %}
        </table>
    </div>
</div>

<div class="row">
    <div class="col-lg">
        <h4><a href="{{cfg().jellyfin_url}}web/index.html#!/userprofiles.html">Jellyfin</a></h4>
        <table class="table table-sm table-bordered">
            <tr>
                <th>Name</th>
                <th>Last Login</th>
                <th>Last Active</th>
                <th>Bandwidth Limit</th>
            </tr>
            {% for user in jellyfin.users|defaultattr("LastLoginDate","")|sort(attribute="LastLoginDate",reverse=True) %}
                <tr>
                    <td>
                        <a href="{{cfg().jellyfin_url}}web/index.html#!/useredit.html?userId={{user.Id}}">
                            {{user.Name}}
                        </a>
                    </td>
                    <td>
                    {% if user.LastLoginDate %}
                            {{user.LastLoginDate|fromiso|ago_dt_utc(2)}} ago
                    {% else %}
                        Never
                    {% endif %}
                    </td>
                    <td>
                    {% if user.LastActivityDate %}
                            {{user.LastActivityDate|fromiso|ago_dt_utc(2)}} ago
                    {% else %}
                        Never
                    {% endif %}
                    </td>
                    <td>
                        {% if user.Policy.RemoteClientBitrateLimit!=0 %}
                            {{user.Policy.RemoteClientBitrateLimit|filesizeformat(binary=False)}}/s
                        {% else %}
                            None
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}